[workspace]
members = [
    "main",
    "fsm",
]
resolver = "3"


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = 3

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

[profile.esp32s2]
inherits = "release"
opt-level = "s"  # Optimize for size.
