[package]
name = "fsm_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
strum = { version = "0.27.1", default-features = false }
strum_macros = { version = "0.27.1", default-features = false }
heapless = "0.8"

[features]
default = ["std"]
std = []

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
